#RUN this command executes the commands in build time
#CMD this command executes the commands in run time
FROM python:3.12-slim

RUN python -m venv /opt/venv/

ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /app 

COPY requirements.txt /tmp/requirements.txt

RUN pip install -r /tmp/requirements.txt

COPY ./src /app 
